const defaultUserInfo = {
    uid: '0',
    max: '0',
    ltime: '0',
    wealth: '0',
    coin: '0',
    utype: '0',
    acttime: '0',
    utypetm: '0',
    status: '0',
    coinall: '0',
    wealthall: '0',
    uoption: {
        username: '',
        isbundmobile: '0',
        picuser: '',
        identity: '',
    },
    alias: '',
    rid: '',
    integral: '0',
    fid: '0',
    userfrom: '0',
    nextrank: '',
    coinlate: '',
    wealthrank: '0',
    wealtlate: '0',
    coinrank: '0',
    honorrank: '0',
    isfollow: '0',
    ismfollow: '0',
    follownum: '0',
    fansnum: '0',
    isfriend: '0',
    remark: '',
    isBadUser: '0',
    picuser: '',
    isLive: '0',
    isVoiceAnchor: '0',
    isAnchor: '0',
    poster: '',
    livetype: '0',
    tplType: '0',
    imIsLive: '0',
    sex: '',
    birthday: '',
    age: '',
    lifePhoto: [],
    coinstep: '0',
    wealthstep: '0',
    constellation: '',
    userMood: '',
    title: '',
    isRealName: '0',
    isPerfect: '0',
};

export { defaultUserInfo };
export default function orizeInfo(info) {
    return defaultUserInfo;
}
